# Generated by Django 3.0.4 on 2020-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsr2',
            name='gstId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم المشارك'),
        ),
    ]
