# Generated by Django 3.0.4 on 2020-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsr',
            name='cho_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AlterField(
            model_name='mainsr',
            name='cho_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AlterField(
            model_name='mainsr',
            name='cho_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AlterField(
            model_name='mainsr',
            name='cho_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
    ]
