# Generated by Django 3.0.4 on 2020-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_mainsr2_gstid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsr',
            name='sr_status',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=True, help_text='يظهز السؤال في الإستبيان', null=True, verbose_name='الحالة'),
        ),
    ]
