# Generated by Django 3.0.4 on 2020-03-17 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200317_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsr',
            name='gstId',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='رقم المشارك'),
        ),
    ]
