# Generated by Django 3.0.4 on 2020-03-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200317_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSr2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_ser1', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة')),
                ('cho1_1', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي')),
                ('cho1_2', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما')),
                ('cho1_3', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي')),
                ('cho1_4', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم')),
                ('sr_ser2', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة')),
                ('cho2_1', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي')),
                ('cho2_2', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما')),
                ('cho2_3', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي')),
                ('cho2_4', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم')),
                ('sr_ser3', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة')),
                ('cho3_1', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي')),
                ('cho3_2', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما')),
                ('cho3_3', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي')),
                ('cho3_4', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم')),
                ('sr_ser4', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة')),
                ('cho4_1', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي')),
                ('cho4_2', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما')),
                ('cho4_3', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي')),
                ('cho4_4', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم')),
                ('sr_ser5', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة')),
                ('cho5_1', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي')),
                ('cho5_2', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما')),
                ('cho5_3', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي')),
                ('cho5_4', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم')),
            ],
        ),
    ]
