# Generated by Django 3.0.4 on 2020-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsr2',
            name='cho10_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho11_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho12_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho13_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho14_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho15_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho16_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho17_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho18_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho19_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho1_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho20_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho21_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho2_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho3_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho4_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho5_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho6_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho7_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho8_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainsr2',
            name='cho9_1',
            field=models.CharField(blank=True, default=False, max_length=5, null=True),
        ),
    ]
