# Generated by Django 3.0.4 on 2020-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_mainsr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsr2',
            name='cho10_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho10_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho10_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho10_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho11_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho11_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho11_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho11_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho12_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho12_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho12_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho12_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho13_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho13_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho13_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho13_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho14_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho14_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho14_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho14_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho15_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho15_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho15_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho15_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho16_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho16_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho16_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho16_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho17_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho17_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho17_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho17_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho6_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho6_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho6_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho6_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho7_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho7_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho7_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho7_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho8_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho8_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho8_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho8_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho9_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho9_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho9_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho9_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='gst_comm',
            field=models.TextField(blank=True, null=True, verbose_name='المقترحات'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser11',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser12',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser13',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser14',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser15',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser16',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser17',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser18',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
    ]
