# Generated by Django 3.0.4 on 2020-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200317_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsr2',
            name='cho18_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho18_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho18_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho18_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho19_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho19_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho19_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho19_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho20_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho20_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho20_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho20_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho21_1',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho21_2',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='مرضي نوعاً ما'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho21_3',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='غير مرضي'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='cho21_4',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, help_text='لا أعلم'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser19',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser20',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser21',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
        migrations.AddField(
            model_name='mainsr2',
            name='sr_ser22',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الخدمة المقدمة'),
        ),
    ]
